# Generated by Django 4.2.13 on 2026-04-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vote",
            name="block_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="vote",
            name="previous_hash",
            field=models.CharField(
                default="0000000000000000000000000000000000000000000000000000000000000000",
                max_length=64,
            ),
        ),
    ]
