# Generated by Django 4.2.13 on 2026-04-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0002_vote_block_hash_vote_previous_hash"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("WARNING", "Warning"),
                            ("CRITICAL", "Critical Breach Attempt"),
                        ],
                        default="WARNING",
                        max_length=20,
                    ),
                ),
                ("action", models.CharField(max_length=255)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("details", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
