# Generated by Django 4.2.30 on 2026-09-07 09:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_securitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledDataPush',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('push_type', models.CharField(default='SYSTEM_LEDGER_AUDIT', max_length=100)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('SKIPPED', 'Skipped (Interval Not Reached)'), ('FAILED', 'Failed')], max_length=20)),
                ('executed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_successful_push', models.DateTimeField(blank=True, null=True)),
                ('details', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scheduled Data Push',
                'verbose_name_plural': 'Scheduled Data Pushes',
                'ordering': ['-executed_at'],
            },
        ),
    ]
