# Generated by Django 4.2.30 on 2026-09-07 10:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_scheduleddatapush'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateAutomationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voting.candidate')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_automations', to='voting.election')),
            ],
            options={
                'verbose_name': 'Candidate Automation Log',
                'verbose_name_plural': 'Candidate Automation Logs',
                'ordering': ['-last_generated_at'],
            },
        ),
    ]
