# Generated by Django 4.2.30 on 2026-09-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_candidateautomationstate'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['election', 'name'], name='idx_candidate_election_name'),
        ),
        migrations.AddIndex(
            model_name='candidateautomationstate',
            index=models.Index(fields=['election', '-last_generated_at'], name='idx_candauto_elec_time'),
        ),
        migrations.AddIndex(
            model_name='election',
            index=models.Index(fields=['start_time', 'end_time'], name='idx_election_active'),
        ),
        migrations.AddIndex(
            model_name='election',
            index=models.Index(fields=['-start_time'], name='idx_election_start'),
        ),
        migrations.AddIndex(
            model_name='scheduleddatapush',
            index=models.Index(fields=['status', '-executed_at'], name='idx_datapush_status_time'),
        ),
        migrations.AddIndex(
            model_name='securitylog',
            index=models.Index(fields=['-timestamp'], name='idx_seclog_timestamp'),
        ),
        migrations.AddIndex(
            model_name='securitylog',
            index=models.Index(fields=['level', '-timestamp'], name='idx_seclog_level_time'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['election', 'id'], name='idx_vote_election_id'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['election', '-id'], name='idx_vote_election_latest'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['voted_at'], name='idx_vote_voted_at'),
        ),
    ]
